import '../styles/globals.css'; 
import type { Metadata } from 'next'; 
import Providers from './GlobalRedux/provider';
import NavBar from '@/components/NavBar';
import Provider from '@/components/Provider';

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <Providers>
                <>
                  <NavBar /> 
                  { children }  
                </>
          </Providers>
        </Provider>
      </body>
    </html>
  )
}
